---
title: "Species Explorer"
author: "John"
date: "02/12/2019"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(shiny)
library(dplyr)
# source("db_extract.R")
# the_data <- GetTheData()
```

The only purpose of Species Explorer is to get information from the database about species frequency in the assessed Mesotrophic Grassland communities. It is interactive: selecting a species from the drop-down list gives a display of frequency compared with the NVC standard, and a downloadable table of the results.

```{r, echo=FALSE}
selectInput("Species", "Choose a species", 
            choices <-  (the_data %>% select(species_name) 
                       %>% distinct() 
                       %>% arrange(species_name))
)
textOutput("Selected")
tableOutput("table")

output$Selected <- renderText({
  paste("You chose", input$Species)
})

# the_table <- reactive
# ({
#     d <- FrequencyByAssembly(the_data)
#     d1 <- left_join(d, the_data %>% select(species_name, species_id) %>% distinct(), by = "species_name")
#     d2 <- left_join(d1, std_freqs, by = c("species_id", "community"))
#     d2 %>% filter(species_name == input$Species) %>% select(assembly_id, assembly_name, community, freq, CrI5, median, CrI95, p_central)
# })

the_table <- reactive({
FrequencyByAssembly(the_data) %>% filter(species_name == input$Species) %>% select(assembly_id, assembly_name, community, freq, CrI5, median, CrI95)

})

# Table of selected species ----
output$table <- renderTable({the_table()})
```

 